// Generated by Hebron at 12/26/2021 1:58:08 AM

use std;
use c_runtime;
use crate::*;

#[derive(Debug, Copy, Clone)]
pub struct stbi__gif {
	pub w:i32,
	pub h:i32,
	pub out:*mut u8,
	pub background:*mut u8,
	pub history:*mut u8,
	pub flags:i32,
	pub bgindex:i32,
	pub ratio:i32,
	pub transparent:i32,
	pub eflags:i32,
	pub pal:[[u8;256];4],
	pub lpal:[[u8;256];4],
	pub codes:[stbi__gif_lzw;8192],
	pub color_table:*mut u8,
	pub parse:i32,
	pub step:i32,
	pub lflags:i32,
	pub start_x:i32,
	pub start_y:i32,
	pub max_x:i32,
	pub max_y:i32,
	pub cur_x:i32,
	pub cur_y:i32,
	pub line_size:i32,
	pub delay:i32,
}

#[derive(Debug, Copy, Clone)]
pub struct stbi__gif_lzw {
	pub prefix:i16,
	pub first:u8,
	pub suffix:u8,
}

impl std::default::Default for stbi__gif {
	fn default() -> Self {
		stbi__gif {
			w: 0,
			h: 0,
			out: std::ptr::null_mut(),
			background: std::ptr::null_mut(),
			history: std::ptr::null_mut(),
			flags: 0,
			bgindex: 0,
			ratio: 0,
			transparent: 0,
			eflags: 0,
			pal: [[0;256];4],
			lpal: [[0;256];4],
			codes: [stbi__gif_lzw::default();8192],
			color_table: std::ptr::null_mut(),
			parse: 0,
			step: 0,
			lflags: 0,
			start_x: 0,
			start_y: 0,
			max_x: 0,
			max_y: 0,
			cur_x: 0,
			cur_y: 0,
			line_size: 0,
			delay: 0,
		}
	}
}

impl std::default::Default for stbi__gif_lzw {
	fn default() -> Self {
		stbi__gif_lzw {
			prefix: 0,
			first: 0,
			suffix: 0,
		}
	}
}

