// Generated by Hebron at 12/26/2021 1:58:08 AM

use std;
use c_runtime;
use crate::*;

#[derive(Debug, Copy, Clone)]
pub struct stbi__bmp_data {
	pub bpp:i32,
	pub offset:i32,
	pub hsz:i32,
	pub mr:u32,
	pub mg:u32,
	pub mb:u32,
	pub ma:u32,
	pub all_a:u32,
	pub extra_read:i32,
}

impl std::default::Default for stbi__bmp_data {
	fn default() -> Self {
		stbi__bmp_data {
			bpp: 0,
			offset: 0,
			hsz: 0,
			mr: 0,
			mg: 0,
			mb: 0,
			ma: 0,
			all_a: 0,
			extra_read: 0,
		}
	}
}

