// Generated by Hebron at 12/26/2021 1:58:08 AM

use std;
use c_runtime;
use crate::*;

#[derive(Debug, Copy, Clone)]
pub struct stbi__huffman {
	pub fast:[u8;512],
	pub code:[u16;256],
	pub values:[u8;256],
	pub size:[u8;257],
	pub maxcode:[u32;18],
	pub delta:[i32;17],
}

#[derive(Debug, Copy, Clone)]
pub struct stbi__jpeg {
	pub s:*mut stbi__context,
	pub huff_dc:[stbi__huffman;4],
	pub huff_ac:[stbi__huffman;4],
	pub dequant:[[u16;4];64],
	pub fast_ac:[[i16;4];512],
	pub img_h_max:i32,
	pub img_v_max:i32,
	pub img_mcu_x:i32,
	pub img_mcu_y:i32,
	pub img_mcu_w:i32,
	pub img_mcu_h:i32,
	pub img_comp:[stbi__jpeg_unnamed1;4],
	pub code_buffer:u32,
	pub code_bits:i32,
	pub marker:u8,
	pub nomore:i32,
	pub progressive:i32,
	pub spec_start:i32,
	pub spec_end:i32,
	pub succ_high:i32,
	pub succ_low:i32,
	pub eob_run:i32,
	pub jfif:i32,
	pub app14_color_transform:i32,
	pub rgb:i32,
	pub scan_n:i32,
	pub order:[i32;4],
	pub restart_interval:i32,
	pub todo:i32,
	pub idct_block_kernel:*mut fn(arg0: *mut u8, arg1: i32, arg2: *mut i16),
	pub YCbCr_to_RGB_kernel:*mut fn(arg0: *mut u8, arg1: *mut u8, arg2: *mut u8, arg3: *mut u8, arg4: i32, arg5: i32),
	pub resample_row_hv_2_kernel:*mut fn(arg0: *mut u8, arg1: *mut u8, arg2: *mut u8, arg3: i32, arg4: i32) -> *mut u8,
}

#[derive(Debug, Copy, Clone)]
pub struct stbi__jpeg_unnamed1 {
	pub id:i32,
	pub h:i32,
	pub v:i32,
	pub tq:i32,
	pub hd:i32,
	pub ha:i32,
	pub dc_pred:i32,
	pub x:i32,
	pub y:i32,
	pub w2:i32,
	pub h2:i32,
	pub data:*mut u8,
	pub raw_data:*mut u8,
	pub raw_coeff:*mut u8,
	pub linebuf:*mut u8,
	pub coeff:*mut i16,
	pub coeff_w:i32,
	pub coeff_h:i32,
}

#[derive(Debug, Copy, Clone)]
pub struct stbi__resample {
	pub resample:*mut fn(arg0: *mut u8, arg1: *mut u8, arg2: *mut u8, arg3: i32, arg4: i32) -> *mut u8,
	pub line0:*mut u8,
	pub line1:*mut u8,
	pub hs:i32,
	pub vs:i32,
	pub w_lores:i32,
	pub ystep:i32,
	pub ypos:i32,
}

impl std::default::Default for stbi__huffman {
	fn default() -> Self {
		stbi__huffman {
			fast: [0;512],
			code: [0;256],
			values: [0;256],
			size: [0;257],
			maxcode: [0;18],
			delta: [0;17],
		}
	}
}

impl std::default::Default for stbi__jpeg {
	fn default() -> Self {
		stbi__jpeg {
			s: std::ptr::null_mut(),
			huff_dc: [stbi__huffman::default();4],
			huff_ac: [stbi__huffman::default();4],
			dequant: [[0;4];64],
			fast_ac: [[0;4];512],
			img_h_max: 0,
			img_v_max: 0,
			img_mcu_x: 0,
			img_mcu_y: 0,
			img_mcu_w: 0,
			img_mcu_h: 0,
			img_comp: [stbi__jpeg_unnamed1::default();4],
			code_buffer: 0,
			code_bits: 0,
			marker: 0,
			nomore: 0,
			progressive: 0,
			spec_start: 0,
			spec_end: 0,
			succ_high: 0,
			succ_low: 0,
			eob_run: 0,
			jfif: 0,
			app14_color_transform: 0,
			rgb: 0,
			scan_n: 0,
			order: [0;4],
			restart_interval: 0,
			todo: 0,
			idct_block_kernel: std::ptr::null_mut(),
			YCbCr_to_RGB_kernel: std::ptr::null_mut(),
			resample_row_hv_2_kernel: std::ptr::null_mut(),
		}
	}
}

impl std::default::Default for stbi__jpeg_unnamed1 {
	fn default() -> Self {
		stbi__jpeg_unnamed1 {
			id: 0,
			h: 0,
			v: 0,
			tq: 0,
			hd: 0,
			ha: 0,
			dc_pred: 0,
			x: 0,
			y: 0,
			w2: 0,
			h2: 0,
			data: std::ptr::null_mut(),
			raw_data: std::ptr::null_mut(),
			raw_coeff: std::ptr::null_mut(),
			linebuf: std::ptr::null_mut(),
			coeff: std::ptr::null_mut(),
			coeff_w: 0,
			coeff_h: 0,
		}
	}
}

impl std::default::Default for stbi__resample {
	fn default() -> Self {
		stbi__resample {
			resample: std::ptr::null_mut(),
			line0: std::ptr::null_mut(),
			line1: std::ptr::null_mut(),
			hs: 0,
			vs: 0,
			w_lores: 0,
			ystep: 0,
			ypos: 0,
		}
	}
}

