// Generated by Hebron at 12/26/2021 1:58:08 AM

use std;
use c_runtime;
use crate::*;

#[derive(Debug, Copy, Clone)]
pub struct stbi__zbuf {
	pub zbuffer:*mut u8,
	pub zbuffer_end:*mut u8,
	pub num_bits:i32,
	pub code_buffer:u32,
	pub zout:*mut i8,
	pub zout_start:*mut i8,
	pub zout_end:*mut i8,
	pub z_expandable:i32,
	pub z_length:stbi__zhuffman,
	pub z_distance:stbi__zhuffman,
}

#[derive(Debug, Copy, Clone)]
pub struct stbi__zhuffman {
	pub fast:[u16;512],
	pub firstcode:[u16;16],
	pub maxcode:[i32;17],
	pub firstsymbol:[u16;16],
	pub size:[u8;288],
	pub value:[u16;288],
}

impl std::default::Default for stbi__zbuf {
	fn default() -> Self {
		stbi__zbuf {
			zbuffer: std::ptr::null_mut(),
			zbuffer_end: std::ptr::null_mut(),
			num_bits: 0,
			code_buffer: 0,
			zout: std::ptr::null_mut(),
			zout_start: std::ptr::null_mut(),
			zout_end: std::ptr::null_mut(),
			z_expandable: 0,
			z_length: stbi__zhuffman::default(),
			z_distance: stbi__zhuffman::default(),
		}
	}
}

impl std::default::Default for stbi__zhuffman {
	fn default() -> Self {
		stbi__zhuffman {
			fast: [0;512],
			firstcode: [0;16],
			maxcode: [0;17],
			firstsymbol: [0;16],
			size: [0;288],
			value: [0;288],
		}
	}
}

