// Generated by Hebron at 12/26/2021 1:58:08 AM

use std;
use c_runtime;
use crate::*;

pub const STBI__F_avg: i32 = 3;

pub const STBI__F_avg_first: i32 = 5;

pub const STBI__F_none: i32 = 0;

pub const STBI__F_paeth: i32 = 4;

pub const STBI__F_paeth_first: i32 = 6;

pub const STBI__F_sub: i32 = 1;

pub const STBI__F_up: i32 = 2;

#[derive(Debug, Copy, Clone)]
pub struct stbi__png {
	pub s:*mut stbi__context,
	pub idata:*mut u8,
	pub expanded:*mut u8,
	pub out:*mut u8,
	pub depth:i32,
}

#[derive(Debug, Copy, Clone)]
pub struct stbi__pngchunk {
	pub length:u32,
	pub _type_:u32,
}

impl std::default::Default for stbi__png {
	fn default() -> Self {
		stbi__png {
			s: std::ptr::null_mut(),
			idata: std::ptr::null_mut(),
			expanded: std::ptr::null_mut(),
			out: std::ptr::null_mut(),
			depth: 0,
		}
	}
}

impl std::default::Default for stbi__pngchunk {
	fn default() -> Self {
		stbi__pngchunk {
			length: 0,
			_type_: 0,
		}
	}
}

